module AStar
  VERSION: String

  class Result < ::Data
    def self.new: (Float score, Array path, Array visited) -> instance
                | (score: Float, path: Array, visited: Array) -> instance

    attr_reader score: Float

    attr_reader path: Array

    attr_reader visited: Array
  end

  def self.traverse: (start: Object, goal: Proc, neighbors: Proc, ?heuristic: Proc, ?weight: Proc, ?visit: Proc) -> Data
end
